#!/usr/bin/env bash
# Installs and configures HAproxy with version 1.5 or greater
#+ in order to send trafic to web-01 and web-02
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  kenmind-alx_front
        bind *:80
        mode http
        default_backend kenmind-alx_back
backend kenmind-alx_back
        balance roundrobin
        server 2191-web-01 3.229.113.167:80 check
        server 2191-web-02 3.234.210.158:80 check
"
 echo "$server_config" >> /etc/haproxy/haproxy.cfg

 echo "ENABLED=1" >> /etc/default/haproxy

 sudo service haproxy restart
